#include "const/character.h"

const struct WeightedItem ItemListSword[] = {
	{ITEM_SWORD_IRON, 70},
	{ITEM_SWORD_STEEL, 25},
	{ITEM_SWORD_SILVER, 5}
};

const struct WeightedItem ItemListLance[] = {
	{ITEM_LANCE_IRON, 70},
	{ITEM_LANCE_STEEL, 25},
	{ITEM_LANCE_SILVER, 5}
};

const struct WeightedItem ItemListAxe[] = {
	{ITEM_AXE_IRON, 70},
	{ITEM_AXE_STEEL, 25},
	{ITEM_AXE_SILVER, 5}
};

const struct WeightedItem ItemListBow[] = {
	{ITEM_BOW_IRON, 70},
	{ITEM_BOW_STEEL, 25},
	{ITEM_BOW_SILVER, 5}
};

const struct WeightedItem ItemListStaff[] = {
	{ITEM_STAFF_HEAL, 70},
	{ITEM_STAFF_MEND, 25},
	{ITEM_STAFF_PHYSIC, 5}
};

const struct WeightedItem ItemListAnima[] = {
	{ITEM_ANIMA_FIRE, 70},
	{ITEM_ANIMA_THUNDER, 25},
	{ITEM_ANIMA_ELFIRE, 5}
};

const struct WeightedItem ItemListLight[] = {
	{ITEM_LIGHT_LIGHTNING, 70},
	{ITEM_LIGHT_SHINE, 25},
	{ITEM_LIGHT_DIVINE, 5}
};

const struct WeightedItem ItemListDark[] = {
	{ITEM_DARK_FLUX, 70},
	{ITEM_DARK_NOSFERATU, 25},
	{ITEM_DARK_LUNA, 5}
};

const struct WeightedItem* const ItemListList[] = {
	ItemListSword,
	ItemListLance,
	ItemListAxe,
	ItemListBow,
	ItemListStaff,
	ItemListAnima,
	ItemListLight,
	ItemListDark	
};

enum Games {
	GAME_FE8,
	GAME_FE7,
	GAME_FE6,
	GAME_FE5
};

const u8 FE8CharacterList[] = {
	CHARACTER_EIRIKA,
	CHARACTER_SETH,
	CHARACTER_GILLIAM,
	CHARACTER_FRANZ,
	CHARACTER_MOULDER,
	CHARACTER_VANESSA,
	CHARACTER_ROSS,
	CHARACTER_NEIMI,
	CHARACTER_COLM,
	CHARACTER_GARCIA,
	CHARACTER_INNES,
	CHARACTER_LUTE,
	CHARACTER_NATASHA,
	CHARACTER_CORMAG,
	CHARACTER_EPHRAIM,
	CHARACTER_FORDE,
	CHARACTER_KYLE,
	CHARACTER_AMELIA,
	CHARACTER_ARTUR,
	CHARACTER_GERIK,
	CHARACTER_TETHYS,
	CHARACTER_MARISA,
	CHARACTER_SALEH,
	CHARACTER_EWAN,
	CHARACTER_LARACHEL,
	CHARACTER_DOZLA,
	CHARACTER_RENNAC,
	CHARACTER_DUESSEL,
	CHARACTER_MYRRH,
	CHARACTER_KNOLL,
	CHARACTER_JOSHUA,
	CHARACTER_SYRENE,
	CHARACTER_TANA,
	CHARACTER_LYON_CC,
	CHARACTER_ORSON_CC,
	CHARACTER_GLEN_CC,
	CHARACTER_SELENA_CC,
	CHARACTER_VALTER_CC,
	CHARACTER_RIEV_CC,
	CHARACTER_CAELLACH_CC,
	CHARACTER_FADO_CC,
	CHARACTER_ISMAIRE_CC,
	CHARACTER_HAYDEN_CC
};

const u8 FE7CharacterList[] = {
	CHARACTER_ELIWOOD,
	CHARACTER_HECTOR,
	CHARACTER_LYN,
	CHARACTER_RAVEN,
	CHARACTER_GEITZ,
	CHARACTER_GUY,
	CHARACTER_KAREL,
	CHARACTER_DORCAS,
	CHARACTER_BARTRE,
	CHARACTER_OSWIN,
	CHARACTER_FARGUS,
	CHARACTER_WIL,
	CHARACTER_REBECCA,
	CHARACTER_LOUISE,
	CHARACTER_LUICIUS,
	CHARACTER_SERRA,
	CHARACTER_RENAULT,
	CHARACTER_ERK,
	CHARACTER_NINO,
	CHARACTER_PENT,
	CHARACTER_CANAS,
	CHARACTER_KENT,
	CHARACTER_SAIN,
	CHARACTER_LOWEN,
	CHARACTER_MARCUS,
	CHARACTER_PRISCILLA,
	CHARACTER_RATH,
	CHARACTER_FLORINA,
	CHARACTER_FIORA,
	CHARACTER_FARINA,
	CHARACTER_HEATH,
	CHARACTER_VAIDA,
	CHARACTER_HAWKEYE,
	CHARACTER_MATTHEW,
	CHARACTER_JAFFAR,
	CHARACTER_NINIAN,
	CHARACTER_NILS,
	CHARACTER_ATHOS,
	CHARACTER_MERLINUS,
	CHARACTER_UTHER,
	CHARACTER_WALLACE,
	CHARACTER_DART,
	CHARACTER_ISADORA,
	CHARACTER_LEGAULT,
	CHARACTER_KARLA,
	CHARACTER_HARKEN,
	CHARACTER_LEILA,
	CHARACTER_BRAMMIMOND
};
